import os

USER_TABLE = os.environ['USER_TABLE']
USER_GSI_INDEX_USERNAME = os.environ['USER_GSI_INDEX_USERNAME']
JWT_SECRET_KEY = os.environ['JWT_SECRET_KEY']
JWT_EXPIRATION_TIME = 3600*6
JWT_ALGORITHM = "HS256"