service: service-room
org: ${env:ORG}

provider:
  name: aws
  runtime: python3.9
  memorySize: 1024
  timeout: 29
  role: ${env:ROLE}
  environment: #aca ponemos las variables de entorno
    ROOM_TABLE: ${env:ROOM_TABLE}
    ROOM_GSI_INDEX_USERID_ID: ${env:ROOM_GSI_INDEX_USERID_ID}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    ROOM_GSI_INDEX_SHORTCODE: ${env:ROOM_GSI_INDEX_SHORTCODE}


package:
  individually: true
  exclude:
    - .serverless/**
    - .venv/**
    - .idea/**
    - financial-data/**
    - build_layer.sh
    - user/**
    - test/**
    - Dockerfile
    - variables/**
    - businesses_businessId_ai-parse/**
    - "*.zip"
    - README.md
    - serverless.yml
    - requirements.txt

layers:
  commonLib:
    package:
      artifact: layer_common_lib.zip
    description: "Dependencias comunes para todas las Lambdas"

functions:
  create:
    handler: create/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
    events:
      - http:
          path: rooms/create
          method: post
          cors:
            origin: '*'
            methods:
              - POST
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  get_room:
    handler: get_room/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
    events:
      - http:
          path: rooms/{roomId}
          method: get
          cors:
            origin: '*'
            methods:
              - GET
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  delete_room:
    handler: delete_room/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
    events:
      - http:
          path: rooms/{roomId}
          method: delete
          cors:
            origin: '*'
            methods:
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  get_room_code:
    handler: get_room_code/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
    events:
      - http:
          path: rooms/code/{code}
          method: get
          cors:
            origin: '*'
            methods:
              - GET
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  get_rooms:
    handler: get_rooms/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
    events:
      - http:
          path: rooms
          method: get
          cors:
            origin: '*'
            methods:
              - GET
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent


  sqs_consumer:
    handler: sqs_consumer/handler.lambda_handler
    layers:
      - { Ref: CommonLibLambdaLayer }
